"""add company_profiles table and conversation summary

Revision ID: 2b24b1676e59
Revises: f9b659a2b8e6
Create Date: 2026-03-30 21:04:58.511709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b24b1676e59'
down_revision: Union[str, None] = 'f9b659a2b8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.Enum('agriculture', 'energie', 'recyclage', 'transport', 'construction', 'textile', 'agroalimentaire', 'services', 'commerce', 'artisanat', 'autre', name='sector_type', create_constraint=True), nullable=True),
    sa.Column('sub_sector', sa.Text(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_xof', sa.BigInteger(), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('has_waste_management', sa.Boolean(), nullable=True),
    sa.Column('has_energy_policy', sa.Boolean(), nullable=True),
    sa.Column('has_gender_policy', sa.Boolean(), nullable=True),
    sa.Column('has_training_program', sa.Boolean(), nullable=True),
    sa.Column('has_financial_transparency', sa.Boolean(), nullable=True),
    sa.Column('governance_structure', sa.Text(), nullable=True),
    sa.Column('environmental_practices', sa.Text(), nullable=True),
    sa.Column('social_practices', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_user_id'), 'company_profiles', ['user_id'], unique=True)
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary')
    op.drop_index(op.f('ix_company_profiles_user_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    sa.Enum(name='sector_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
